# Generated by Django 4.2 on 2023-04-30 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=300, null=True)),
                ('rating', models.FloatField(null=True)),
                ('mrp', models.FloatField(null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('size', models.CharField(max_length=25, null=True)),
                ('metadata', models.JSONField()),
                ('brand_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_brand')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_categories')),
            ],
        ),
    ]
