# Generated by Django 4.2 on 2023-05-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_purchase_order_unchecked_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_brand',
            name='brand_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product_categories',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
