# Generated by Django 4.2 on 2023-05-08 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_purchase_order_order_detail_file_and_more'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='product_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_stock', models.IntegerField()),
                ('unchecked_stock', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_details')),
            ],
        ),
    ]
