# Generated by Django 4.2 on 2023-05-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_unchecked_stock_cosp_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='metadata',
            field=models.JSONField(null=True),
        ),
    ]
