# Generated by Django 4.2 on 2023-05-08 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_brand_brand_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_qc_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_status', models.CharField(max_length=100, unique=True)),
                ('qc_details', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='checked_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sosp', models.FloatField(null=True)),
                ('cosp', models.FloatField(null=True)),
                ('mbp', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_details')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.purchase_order')),
            ],
        ),
    ]
