# Generated by Django 4.2 on 2023-05-11 07:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_qc_status_checked_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='checked_stock',
            name='qc_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_qc_status'),
        ),
        migrations.AddField(
            model_name='product_details',
            name='model',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product_details',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checked_stock',
            name='purchase_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.purchase_order'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
