# Generated by Django 4.2 on 2023-05-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_checked_stock_qc_status_product_details_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='unchecked_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.CharField(max_length=100, null=True)),
                ('quantity', models.IntegerField()),
                ('sosp', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('online_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_details')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.purchase_order')),
            ],
        ),
    ]
