# Generated by Django 4.2 on 2023-05-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_unchecked_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='checked_stock',
            name='sold_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='unchecked_stock',
            name='checked_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
