# Generated by Django 4.2 on 2023-05-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_checked_stock_sold_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checked_stock',
            name='sold_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='unchecked_stock',
            name='checked_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
