# Generated by Django 4.2 on 2023-05-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_checked_stock_sold_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_stock',
            name='checked_stock',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product_stock',
            name='unchecked_stock',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
