# Generated by Django 4.2 on 2023-05-16 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_stock_checked_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_stock',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product_details'),
        ),
    ]
