# Generated by Django 4.2 on 2023-07-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_checked_stock_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_qc_status',
            name='qc_code',
            field=models.CharField(default='FRH',unique=True, max_length=3),
        ),
    ]
