# Generated by Django 4.2 on 2023-07-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_qc_status_qc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checked_stock',
            name='barcode',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
