# Generated by Django 4.2 on 2023-05-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_transaction_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
