# Generated by Django 4.2 on 2023-06-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_transaction_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='voucher_object_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
