# Generated by Django 4.2 on 2023-07-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_transaction_is_active'),
        ('product', '0020_remove_sale_bill_account_id_and_more'),
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='sale_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=25)),
                ('product_qty', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
        ),
        migrations.CreateModel(
            name='product_sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('price_per_piece', models.DecimalField(decimal_places=2, max_digits=25)),
                ('checked_stock_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.checked_stock')),
                ('sale_bill_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sale_bill')),
            ],
        ),
    ]
