# Generated by Django 4.2 on 2023-07-14 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_sale_bill_account_id_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_returned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('price_per_piece', models.DecimalField(decimal_places=2, max_digits=25)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_details')),
                ('sale_bill_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sale_bill')),
            ],
        ),
    ]
