# Generated by Django 4.2 on 2023-07-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_product_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_returned',
            name='reason',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
