# Generated by Django 4.2 on 2023-07-26 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_product_returned_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_returned',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
